print("this is the print function, it simply prints text")
response = input("this is the input function, you can reply to this, hello you! ")
if response in ["hello", "hi", "hey"]:
    print(f"within an input function, i had an if statement, you said {response}, which was within the list of potential responses, so now we are here! cool right? ")
else: print("you said something that was not in the list of potential responses, so we are here instead!")
import time
time.sleep(2)
print("i just used the time function to make a pause.")
time.sleep(1)
name = input("so, whats your name? ")
print(f"cool, we've made it pretty far huh {name}? ")
time.sleep(1)
name2 = input("I'm going to ask for your name again, but this time, type it with a couple of extra spaces ").strip().title()
# name2 = name2.strip().title() this also goes
# you can put title and strip as a chain to the input function
#.title is a function/method that capitalizes the first letter of each word in a string, and makes the rest of the letters lowercase.   
#.strip is a function/method that that removes any extra spaces
time.sleep(1)
input (f"So your name is {name2} right? ") 
time.sleep(1) 
name3 = input (f"what's your full name {name2}?").strip().title()
#now lets split first name and last name
first_name, last_name = name3.split(" ")
input(f"so your first name is {first_name} and your last name is {last_name} right? " )
print("great, lets start doing math now!")
time.sleep(1)
num1 = int(input("enter a number "))
num2 = int(input("enter another number "))
print(f"the sum of {num1} and {num2} is {num1 + num2} ")
print(f"the difference of {num1} and {num2} is {num1 - num2} ")
print(f"the product of {num1} and {num2} is {num1 * num2} ")
print(f"the quotient of {num1} and {num2} is {num1 / num2} ")
time.sleep(1)
print("we used int() to convert the input from a string to an integer, so that we could do math with it!")
time.sleep(1)
import math
print("without int(), we would have been concatenating the two numbers as strings instead of adding them together.  for example, if we had entered 5 and 10, without int(), the sum would have been '510' instead of 15.") 
time.sleep(1)
num3 = int(input("enter a number to find its square root "))
print(f"the square root of {num3} is {math.sqrt(num3)} ")
time.sleep(2)
print("we imported the math module to use the sqrt function, which calculates the square root of a number.")
time.sleep(2)
num4 = float(input("enter a number with a decimal "))
print(f"{num1 + num4} is the sum of {num1} and {num4} ")
print("we used float() to convert the input from a string to a floating point number, which allows us to do math with decimals.")
time.sleep(2)
print(f"we can also round numbers to a certain number of decimal places using the round() function. for example, if we wanted to round the sum of {num1} and {num4} to 2 decimal places, we could do this: {round(num1 + num4, 2)}")
time.sleep(2)
print("phew, this is alot. lets keep going")
time.sleep(2)
print("remember that you can also define the sum of two numbers as a variable. like z = num1 + num2.")
time.sleep(2)
print("you ever heard of defining functions? its a way to create reusable blocks of code")
def greet(name):
    print(f"hello {name}, nice to meet you!")
greet(name2)
time.sleep(1)
print("we defined a function called greet that takes in a parameter called name, and when we call the function with a name, it prints a greeting message.")
time.sleep(1)
print("we've finally made it to the end of the first lecture, nice! 63 lines total.")
time.sleep(1) 
print(" well done keep this file as is, make a new one for the next lecture")

